### ISSUE TITLE
Name the different types of questions

### ISSUE THREAD

**Issue by rovaughn** [spencersnygg/VoteWise#16]
There seem to be three different kinds of questions: agreement/importance questions, ranking questions, and short answer questions.

Can we define all the different types and decide on canonical names for them?  It would help with structuring the database.

**Comment by spencersnygg** [comment]
Yes.  Agreement is one form of questions.  Ranking is another form of questions.  Fill in the blank is another type of question.  All of these questions are multipart in that all of them allow you to say how important the question is and add your own comments.

**Comment by rovaughn** [comment]
Before we close this issue, to summarize, the three kinds of questions we need by October 1 are (from most to least important):

1. Concurrence (agree/disagree)
2. Ranking
3. Judge
